version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/redis:5

    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: pip install -e .[test]

      - run: pytest --junitxml=test-reports/junit.xml --verbose --showlocals --color=yes
      - store_test_results:
          path: test-reports
